# gmp = "Gustavo" #Tipo string (str)
# idade = 20 #Tipo inteiro (int)
# altura = 1.70 #Tipo decimal (float)
# matriculado = True #Tipo boleano (bool)

# type(idade) 

# print(type(idade)) 
# print(type(idade)) 
# print(type(idade)) 
# print(type(idade)) 
# print(type(idade)) 

numero1 = 8
numero2 = 6

print(numero1+numero2) 
print(numero1-numero2) 
print(numero1*numero2) 
print(numero1/numero2) 
print(numero1//numero2) 
print(numero1%numero2) 
print(numero1% 2)

n1 = 9
n2 = 4

print(n1 == n2) 
print(n1 != n2) 
print(n1 > n2) 
print(n1 < n2) 
print(n1 >= n2) 

gmp = input("Digite o seu nome: ")

print("Bem vindo")
print(f"Bem vindo {gmp}!")
